Adding step Verify Stripe key in build output

diff --git a/.github/workflows/ci&deploy.yml b/.github/workflows/ci&deploy.yml
--- a/.github/workflows/ci&deploy.yml
+++ b/.github/workflows/ci&deploy.yml
@@ -50,6 +50,11 @@ jobs:
           VITE_API_URL: ${{ secrets.VITE_API_URL }}
         run: npm run build
 
+      - name: Verify Stripe key in build output
+        working-directory: ecommerce-front
+        run: |
+          grep -R "pk_" dist/assets || echo "❌ Stripe key not found in build"
+
       - name: Upload frontend artifact
         uses: actions/upload-artifact@v4
         with:
